spring:
  graphql:
    graphiql:
      enabled: 'true'
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27017
      database: ${MONGO_DATABASE}

logging:
    level:
      org:
        springframework:
          data:
            mongodb:
              core:
                ReactiveMongoTemplate: DEBUG

jwtSecret: ${JWT_SECRET}
jwtExpirationMs: 600000
otpExpirationSeconds: 30